version: '3.8'
services:
  gcp-loader:
    build: .
    container_name: gcp-loader
    volumes:
      - ./datasets:/app/datasets
      - ./sql:/app/sql
      - ./screenshots:/app/screenshots
      - ./gcs.json:/app/gcs.json   # mount the key file directly
    tty: true
    stdin_open: true